export const PAYMENT_HISTORY = [
    {
      studentName: "Jaymes Astrid",
      email: "jaymesastrid1223@testmail.com",
      course: "Project Management",
      amount: "₦50,000",
      date: "08 - 08 - 2024",
    },
    {
      studentName: "Tife Oluwadesi",
      email: "jaymesastrid1223@testmail.com",
      course: "Frontend Development (Expert)",
      amount: "₦150,000",
      date: "08 - 08 - 2024",
    },
    {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "Product Design",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "Backend Development (Basic)",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "QA/Software Testing",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "Product Design",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "Product Design",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "Product Management",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "Product Management",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "Product Management",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "Product Management",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "Product Management",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Jaymes Astrid",
        email: "jaymesastrid1223@testmail.com",
        course: "Project Management",
        amount: "₦50,000",
        date: "08 - 08 - 2024",
      },
      {
        studentName: "Tife Oluwadesi",
        email: "jaymesastrid1223@testmail.com",
        course: "Frontend Development (Expert)",
        amount: "₦150,000",
        date: "08 - 08 - 2024",
      },
      {
          studentName: "Tife Oluwadesi",
          email: "jaymesastrid1223@testmail.com",
          course: "Product Design",
          amount: "₦150,000",
          date: "08 - 08 - 2024",
        },
        {
          studentName: "Tife Oluwadesi",
          email: "jaymesastrid1223@testmail.com",
          course: "Backend Development (Basic)",
          amount: "₦150,000",
          date: "08 - 08 - 2024",
        },
        {
          studentName: "Tife Oluwadesi",
          email: "jaymesastrid1223@testmail.com",
          course: "QA/Software Testing",
          amount: "₦150,000",
          date: "08 - 08 - 2024",
        },
        {
          studentName: "Tife Oluwadesi",
          email: "jaymesastrid1223@testmail.com",
          course: "Product Design",
          amount: "₦150,000",
          date: "08 - 08 - 2024",
        },
        {
          studentName: "Tife Oluwadesi",
          email: "jaymesastrid1223@testmail.com",
          course: "Product Design",
          amount: "₦150,000",
          date: "08 - 08 - 2024",
        },
        {
          studentName: "Tife Oluwadesi",
          email: "jaymesastrid1223@testmail.com",
          course: "Product Management",
          amount: "₦150,000",
          date: "08 - 08 - 2024",
        },
        {
          studentName: "Tife Oluwadesi",
          email: "jaymesastrid1223@testmail.com",
          course: "Frontend Development (Expert)",
          amount: "₦150,000",
          date: "08 - 08 - 2024",
        },
        {
          studentName: "Tife Oluwadesi",
          email: "jaymesastrid1223@testmail.com",
          course: "Product Management",
          amount: "₦150,000",
          date: "08 - 08 - 2024",
        },
        {
          studentName: "Tife Oluwadesi",
          email: "jaymesastrid1223@testmail.com",
          course: "Product Management",
          amount: "₦150,000",
          date: "08 - 08 - 2024",
        },
        {
          studentName: "Tife Oluwadesi",
          email: "jaymesastrid1223@testmail.com",
          course: "Product Management",
          amount: "₦150,000",
          date: "08 - 08 - 2024",
        },
        {
            studentName: "Jaymes Astrid",
            email: "jaymesastrid1223@testmail.com",
            course: "Project Management",
            amount: "₦50,000",
            date: "08 - 08 - 2024",
          },
          {
            studentName: "Tife Oluwadesi",
            email: "jaymesastrid1223@testmail.com",
            course: "Frontend Development (Expert)",
            amount: "₦150,000",
            date: "08 - 08 - 2024",
          },
          {
              studentName: "Tife Oluwadesi",
              email: "jaymesastrid1223@testmail.com",
              course: "Product Design",
              amount: "₦150,000",
              date: "08 - 08 - 2024",
            },
            {
              studentName: "Tife Oluwadesi",
              email: "jaymesastrid1223@testmail.com",
              course: "Backend Development (Basic)",
              amount: "₦150,000",
              date: "08 - 08 - 2024",
            },
            {
              studentName: "Tife Oluwadesi",
              email: "jaymesastrid1223@testmail.com",
              course: "QA/Software Testing",
              amount: "₦150,000",
              date: "08 - 08 - 2024",
            },
            {
              studentName: "Tife Oluwadesi",
              email: "jaymesastrid1223@testmail.com",
              course: "Product Design",
              amount: "₦150,000",
              date: "08 - 08 - 2024",
            },
            {
              studentName: "Tife Oluwadesi",
              email: "jaymesastrid1223@testmail.com",
              course: "Product Design",
              amount: "₦150,000",
              date: "08 - 08 - 2024",
            },
            {
              studentName: "Tife Oluwadesi",
              email: "jaymesastrid1223@testmail.com",
              course: "Product Management",
              amount: "₦150,000",
              date: "08 - 08 - 2024",
            },
            {
              studentName: "Tife Oluwadesi",
              email: "jaymesastrid1223@testmail.com",
              course: "Product Management",
              amount: "₦150,000",
              date: "08 - 08 - 2024",
            },
            {
                studentName: "Jaymes Astrid",
                email: "jaymesastrid1223@testmail.com",
                course: "Project Management",
                amount: "₦50,000",
                date: "08 - 08 - 2024",
              },
              {
                studentName: "Tife Oluwadesi",
                email: "jaymesastrid1223@testmail.com",
                course: "Frontend Development (Expert)",
                amount: "₦150,000",
                date: "08 - 08 - 2024",
              },
              {
                  studentName: "Tife Oluwadesi",
                  email: "jaymesastrid1223@testmail.com",
                  course: "Product Design",
                  amount: "₦150,000",
                  date: "08 - 08 - 2024",
                },
                {
                  studentName: "Tife Oluwadesi",
                  email: "jaymesastrid1223@testmail.com",
                  course: "Backend Development (Basic)",
                  amount: "₦150,000",
                  date: "08 - 08 - 2024",
                },
                {
                  studentName: "Tife Oluwadesi",
                  email: "jaymesastrid1223@testmail.com",
                  course: "QA/Software Testing",
                  amount: "₦150,000",
                  date: "08 - 08 - 2024",
                },
                {
                  studentName: "Tife Oluwadesi",
                  email: "jaymesastrid1223@testmail.com",
                  course: "Product Design",
                  amount: "₦150,000",
                  date: "08 - 08 - 2024",
                },
                {
                  studentName: "Tife Oluwadesi",
                  email: "jaymesastrid1223@testmail.com",
                  course: "Product Design",
                  amount: "₦150,000",
                  date: "08 - 08 - 2024",
                },
                {
                  studentName: "Tife Oluwadesi",
                  email: "jaymesastrid1223@testmail.com",
                  course: "Product Management",
                  amount: "₦150,000",
                  date: "08 - 08 - 2024",
                },
                {
                  studentName: "Tife Oluwadesi",
                  email: "jaymesastrid1223@testmail.com",
                  course: "Product Management",
                  amount: "₦150,000",
                  date: "08 - 08 - 2024",
                },
   
  ];
  